[build]
nixPacks = true

[build.nixpacksPlan]
providers = ["python", "nodejs"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python310", "nodejs_18", "yarn"]

[build.nixpacksPlan.phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[build.nixpacksPlan.start]
cmd = "uvicorn backend.server:app --host 0.0.0.0 --port $PORT"